//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFATURABILGI
    {
        public int ID { get; set; }
        public string SERI { get; set; }
        public string SIRA { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string SAAT { get; set; }
        public Nullable<int> FIRMA { get; set; }
        public Nullable<short> PERSONEL { get; set; }
    
        public virtual TBLFIRMA TBLFIRMA { get; set; }
        public virtual TBLPERSONEL TBLPERSONEL { get; set; }
        public virtual TBLFATURADETAY TBLFATURADETAY { get; set; }
    }
}
