//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLISLEMDETAY
    {
        public int URUNISLEMID { get; set; }
        public Nullable<int> ISLEM { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<decimal> FIYAT { get; set; }
        public string ISLEMLER { get; set; }
    }
}
